<div class="space-y-6">
    <x-ui.breadcrumbs :items="[['label' => 'Examinations'], ['label' => $exam->name], ['label' => 'Question paper']]" />
    <x-ui.page-header :title="$exam->name.' question paper'" description="Build the paper from tenant-scoped question versions. Marks and ordering are validated by the existing actions." />
    @if($message)<x-ui.alert type="success">{{ $message }}</x-ui.alert>@endif
    @if(!$schedule)<x-ui.empty-state title="No exam schedule" message="Create an exam schedule before building its paper." />
    @else
        <x-ui.card title="Add question"><form wire:submit="add" class="grid gap-4 sm:grid-cols-3"><x-ui.select label="Question version" wire:model="form.question_version_id" :error="$errors->first('form.question_version_id')" required><option value="">Choose a question version</option>@foreach($versions as $version)<option value="{{ $version->id }}">{{ $version->question?->stable_key }} · v{{ $version->version }}</option>@endforeach</x-ui.select><x-ui.input type="number" label="Question number" wire:model="form.ordinal" :error="$errors->first('form.ordinal')" min="1" required /><x-ui.input type="number" label="Marks" wire:model="form.marks" :error="$errors->first('form.marks')" min="1" required /><div class="sm:col-span-3"><x-ui.button type="submit" loading="add">Add to paper</x-ui.button></div></form></x-ui.card>
        <x-ui.card title="Paper snapshot" :subtitle="$paper ? 'Total marks: '.$paper->total_marks : 'Add the first question to create the paper.'">@if($paper)<x-ui.data-table caption="Question paper"><thead><tr><th>No.</th><th>Question</th><th>Marks</th><th>Actions</th></tr></thead><tbody>@foreach($paper->questions as $question)<tr><td data-label="No.">{{ $question->ordinal }}</td><td data-label="Question">{{ $question->version?->prompt }}</td><td data-label="Marks">{{ $question->marks }}</td><td data-label="Actions" class="space-x-2"><x-ui.button variant="danger" wire:click="remove({{ $question->id }})" loading="remove">Remove</x-ui.button><x-ui.button variant="secondary" wire:click="reorder({{ $question->id }}, {{ $question->ordinal + 1 }})" loading="reorder">Move down</x-ui.button></td></tr>@endforeach</tbody></x-ui.data-table>@else<x-ui.empty-state title="Paper not started" message="Questions added here become the server-managed paper snapshot." />@endif</x-ui.card>
    @endif
</div>
