<div class="space-y-6">
    <x-ui.breadcrumbs :items="[['label' => 'Academic setup']]" />
    <x-ui.page-header :title="ucwords(str_replace('-', ' ', $screen))" description="Configure tenant-scoped academic relationships using readable labels." />
    @if(in_array($screen, ['class-groups', 'subject-assignments', 'teacher-assignments']))
        <x-ui.alert type="info">Academic years, classes, sections, groups, and subjects are prerequisites maintained by the existing school setup. Select only records from this school.</x-ui.alert>
        <x-ui.card title="Create relationship" subtitle="Selections reset automatically when an upstream prerequisite changes.">
            <form wire:submit="save" class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                @if($screen === 'class-groups')
                    <x-ui.select label="Class" wire:model.live="form.class_id" required><option value="">Choose a class</option>@foreach($classes as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</x-ui.select>
                    <x-ui.select label="Applicable group" wire:model.live="form.group_id" :disabled="!($form['class_id'] ?? null)" required><option value="">{{ ($form['class_id'] ?? null) ? 'Choose a group' : 'Choose a class first' }}</option>@foreach($groups as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</x-ui.select>
                @elseif($screen === 'subject-assignments')
                    <x-ui.select label="Academic year" wire:model.live="form.academic_year_id" required><option value="">Choose a year</option>@foreach($years as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</x-ui.select>
                    <x-ui.select label="Class" wire:model.live="form.class_id" :disabled="!($form['academic_year_id'] ?? null)" required><option value="">{{ ($form['academic_year_id'] ?? null) ? 'Choose a class' : 'Choose a year first' }}</option>@foreach($classes as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</x-ui.select>
                    <x-ui.select label="Subject" wire:model.live="form.subject_id" :disabled="!($form['class_id'] ?? null)" required><option value="">{{ ($form['class_id'] ?? null) ? 'Choose a subject' : 'Choose a class first' }}</option>@foreach($subjects as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</x-ui.select>
                    <x-ui.select label="Optional group" wire:model.live="form.group_id" :disabled="!($form['class_id'] ?? null)"><option value="">All groups</option>@foreach($groups as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</x-ui.select>
                @else
                    <x-ui.select label="Teacher" wire:model.live="form.teacher_id" required><option value="">Choose a teacher</option>@foreach($teachers as $x)<option value="{{ $x->id }}">{{ trim($x->first_name.' '.$x->last_name) }}</option>@endforeach</x-ui.select>
                    <x-ui.select label="Academic year" wire:model.live="form.academic_year_id" required><option value="">Choose a year</option>@foreach($years as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</x-ui.select>
                    <x-ui.select label="Class" wire:model.live="form.class_id" :disabled="!($form['academic_year_id'] ?? null)" required><option value="">{{ ($form['academic_year_id'] ?? null) ? 'Choose a class' : 'Choose a year first' }}</option>@foreach($classes as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</x-ui.select>
                    <x-ui.select label="Section" wire:model.live="form.section_id" :disabled="!($form['class_id'] ?? null)" required><option value="">{{ ($form['class_id'] ?? null) ? 'Choose a section' : 'Choose a class first' }}</option>@foreach($sections as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</x-ui.select>
                    <x-ui.select label="Subject assignment" wire:model.live="form.subject_assignment_id" :disabled="!($form['academic_year_id'] ?? null) || !($form['class_id'] ?? null)" required><option value="">{{ ($subjectAssignments->isNotEmpty()) ? 'Choose a subject assignment' : 'Choose year and class first' }}</option>@foreach($subjectAssignments as $x)<option value="{{ $x->id }}">{{ $x->subject?->name }} — {{ $x->academicClass?->name }} @if($x->group?->name) · {{ $x->group->name }} @endif</option>@endforeach</x-ui.select>
                    <x-ui.select label="Optional group" wire:model.live="form.group_id" :disabled="!($form['class_id'] ?? null)"><option value="">No group</option>@foreach($groups as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</x-ui.select>
                @endif
                <div class="sm:col-span-2 lg:col-span-3">@if($errors->any())<x-ui.alert type="error" title="Please check the form">{{ $errors->first() }}</x-ui.alert>@endif<div class="mt-3"><x-ui.button type="submit" loading="save">Save relationship</x-ui.button></div></div>
            </form>
        </x-ui.card>
    @endif
    @if($screen === 'subject-assignments')
        <x-ui.card title="Subject assignments"><x-ui.data-table caption="Subject assignments"><thead><tr><th>Subject</th><th>Academic year</th><th>Class</th><th>Group</th></tr></thead><tbody>@forelse($records as $record)<tr><td data-label="Subject">{{ $record->subject?->name }}</td><td data-label="Academic year">{{ $record->academicYear?->name }}</td><td data-label="Class">{{ $record->academicClass?->name }}</td><td data-label="Group">{{ $record->group?->name ?? 'All groups' }}</td></tr>@empty<tr><td colspan="4"><x-ui.empty-state title="No subject assignments" message="Create one after choosing an academic year and class." /></td></tr>@endforelse</tbody></x-ui.data-table></x-ui.card>
    @elseif($screen === 'teacher-assignments')
        <x-ui.card title="Teacher assignments"><x-ui.data-table caption="Teacher assignments"><thead><tr><th>Teacher</th><th>Subject</th><th>Academic year</th><th>Class / section</th><th>Group</th></tr></thead><tbody>@forelse($records as $record)<tr><td data-label="Teacher">{{ trim($record->teacher?->first_name.' '.$record->teacher?->last_name) }}</td><td data-label="Subject">{{ $record->subjectAssignment?->subject?->name }}</td><td data-label="Academic year">{{ $record->academicYear?->name }}</td><td data-label="Class / section">{{ $record->academicClass?->name }} · {{ $record->section?->name }}</td><td data-label="Group">{{ $record->group?->name ?? 'All groups' }}</td></tr>@empty<tr><td colspan="5"><x-ui.empty-state title="No teacher assignments" message="Create one after choosing a valid subject assignment." /></td></tr>@endforelse</tbody></x-ui.data-table></x-ui.card>
    @elseif($screen === 'class-groups')
        <x-ui.card title="Configured class groups"><x-ui.data-table caption="Configured class groups"><thead><tr><th>Class</th><th>Group</th></tr></thead><tbody>@forelse($records as $record)<tr><td data-label="Class">{{ $record->academicClass?->name }}</td><td data-label="Group">{{ $record->group?->name }}</td></tr>@empty<tr><td colspan="2"><x-ui.empty-state title="No class groups" message="Choose a class and applicable group above." /></td></tr>@endforelse</tbody></x-ui.data-table></x-ui.card>
    @else
        <x-ui.card title="Records"><x-ui.empty-state title="No records" message="This setup surface is read-only until a supported backend Action is available." /></x-ui.card>
    @endif
</div>
