<div class="space-y-6">
    <x-ui.breadcrumbs :items="[['label' => 'Promotion']]" />
    <x-ui.page-header title="Student promotion" description="Evaluate eligible students, review target placement, and apply promotions through the server-owned workflow." />
    @if($message)<x-ui.alert type="success">{{ $message }}</x-ui.alert>@endif
    @if($errors->any())<x-ui.alert type="error">{{ $errors->first() }}</x-ui.alert>@endif
    <x-ui.card title="Create promotion draft"><form wire:submit="save" class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        <x-ui.select label="Student" wire:model.live="student_id" :error="$errors->first('student_id')" required><option value="">Choose student</option>@foreach($students as $student)<option value="{{ $student->id }}">{{ trim($student->first_name.' '.$student->last_name) }}{{ $student->student_code ? ' · '.$student->student_code : '' }}</option>@endforeach</x-ui.select>
        <x-ui.select label="Source enrollment" wire:model.live="source_enrollment_id" :disabled="!$student_id" :error="$errors->first('source_enrollment_id')" required><option value="">Choose current placement</option>@foreach($enrollments as $enrollment)<option value="{{ $enrollment->id }}">{{ $enrollment->academicYear?->name }} · {{ $enrollment->academicClass?->name }}{{ $enrollment->section?->name ? ' / '.$enrollment->section->name : '' }} · Roll {{ $enrollment->roll ?? '—' }}</option>@endforeach</x-ui.select>
        <x-ui.select label="Target academic year" wire:model.live="target_academic_year_id" :error="$errors->first('target_academic_year_id')" required><option value="">Choose target year</option>@foreach($years as $year)<option value="{{ $year->id }}">{{ $year->name }}</option>@endforeach</x-ui.select>
        <x-ui.select label="Target class" wire:model.live="target_class_id" :disabled="!$target_academic_year_id" :error="$errors->first('target_class_id')" required><option value="">Choose target class</option>@foreach($classes as $class)<option value="{{ $class->id }}">{{ $class->name }}</option>@endforeach</x-ui.select>
        <x-ui.select label="Target section" wire:model="target_section_id" :disabled="$targetSections->isEmpty()" :error="$errors->first('target_section_id')"><option value="">Optional section</option>@foreach($targetSections as $section)<option value="{{ $section->id }}">{{ $section->name }}</option>@endforeach</x-ui.select>
        <div class="flex items-end"><x-ui.button type="submit" loading="save">Save draft</x-ui.button></div>
    </form></x-ui.card>
    <x-ui.card title="Promotion candidates"><x-ui.data-table caption="Promotion candidates"><thead><tr><th>Student / roll</th><th>Current placement</th><th>Target placement</th><th>Eligibility</th><th>Status</th><th>Action</th></tr></thead><tbody>
        @forelse($promotions as $promotion)<tr><td data-label="Student / roll"><span class="font-semibold">{{ trim($promotion->student?->first_name.' '.$promotion->student?->last_name) }}</span><span class="block text-xs text-slate-500">Roll {{ $promotion->sourceEnrollment?->roll ?? '—' }}</span></td><td data-label="Current placement">{{ $promotion->sourceEnrollment?->academicYear?->name }} · {{ $promotion->sourceEnrollment?->academicClass?->name }}{{ $promotion->sourceEnrollment?->section?->name ? ' / '.$promotion->sourceEnrollment->section->name : '' }}</td><td data-label="Target placement">{{ $promotion->targetAcademicYear?->name }} · {{ $promotion->targetClass?->name }}{{ $promotion->targetSection?->name ? ' / '.$promotion->targetSection->name : '' }}</td><td data-label="Eligibility">@if($promotion->eligibility_basis)<x-ui.status-badge status="eligible" />@else<span class="text-sm text-slate-500">Pending evaluation</span>@endif</td><td data-label="Status"><x-ui.status-badge :status="$promotion->status" /></td><td data-label="Action" class="space-x-2">@if($promotion->status === 'draft')<x-ui.button wire:click="evaluate({{ $promotion->id }})" loading="evaluate">Evaluate</x-ui.button>@elseif($promotion->status === 'eligible')<x-ui.button wire:click="approve({{ $promotion->id }})" loading="approve">Approve</x-ui.button>@elseif($promotion->status === 'approved')<x-ui.confirm-dialog title="Apply promotion?" message="A new enrollment will be created and the source enrollment will remain historical." confirm-label="Apply promotion" event="apply({{ $promotion->id }})">Apply promotion</x-ui.confirm-dialog>@elseif($promotion->status === 'applied')<span class="text-sm text-slate-500">Applied · history preserved</span>@else<span class="text-sm text-slate-500">Read-only</span>@endif</td></tr>@empty<tr><td colspan="6"><x-ui.empty-state title="No promotion candidates" message="Create a draft after selecting an active student placement." /></td></tr>@endforelse
    </tbody></x-ui.data-table></x-ui.card>
</div>
