<div class="space-y-6">
    <x-ui.breadcrumbs :items="[['label' => 'Examinations'], ['label' => 'Question bank']]" />
    <x-ui.page-header title="Question bank" description="Maintain reusable, school-scoped questions and versions." />
    @if($message)<x-ui.alert type="success">{{ $message }}</x-ui.alert>@endif
    @if($mode === 'banks')
        <x-ui.card title="Create question bank"><form wire:submit="saveBank" class="grid gap-4 sm:grid-cols-3"><x-ui.input label="Bank name" wire:model="form.name" :error="$errors->first('form.name')" required /><x-ui.select label="Subject" wire:model="form.subject_id" :error="$errors->first('form.subject_id')" required><option value="">Choose subject</option>@foreach($subjects as $subject)<option value="{{ $subject->id }}">{{ $subject->name }}</option>@endforeach</x-ui.select><x-ui.input label="Language" wire:model="form.language" hint="Optional" /><div><x-ui.button type="submit" loading="saveBank">Create bank</x-ui.button></div></form></x-ui.card>
        <x-ui.card title="Question banks"><x-ui.data-table caption="Question banks"><thead><tr><th>Name</th><th>Subject</th><th>Questions</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($banks as $bank)<tr><td data-label="Name">{{ $bank->name }}</td><td data-label="Subject">{{ $subjects->firstWhere('id', $bank->subject_id)?->name }}</td><td data-label="Questions">{{ $bank->questions->count() }}</td><td data-label="Status"><x-ui.status-badge :status="$bank->status" /></td><td data-label="Action"><x-ui.button variant="secondary" wire:click="toggleBank({{ $bank->id }})" loading="toggleBank">{{ $bank->status === 'active' ? 'Deactivate' : 'Activate' }}</x-ui.button></td></tr>@empty<tr><td colspan="5"><x-ui.empty-state title="No question banks" message="Create a bank before adding questions." /></td></tr>@endforelse</tbody></x-ui.data-table></x-ui.card>
    @else
        <x-ui.card title="Create question"><form wire:submit="saveQuestion" class="grid gap-4 sm:grid-cols-3"><x-ui.select label="Question bank" wire:model="form.question_bank_id" :error="$errors->first('form.question_bank_id')" required><option value="">Choose bank</option>@foreach($banks as $bank)<option value="{{ $bank->id }}">{{ $bank->name }}</option>@endforeach</x-ui.select><x-ui.input label="Stable key" wire:model="form.stable_key" :error="$errors->first('form.stable_key')" required /><x-ui.select label="Type" wire:model="form.type" required><option value="mcq">MCQ</option><option value="true_false">True/False</option><option value="short_answer">Short answer</option><option value="descriptive">Descriptive</option></x-ui.select><div><x-ui.button type="submit" loading="saveQuestion">Create question</x-ui.button></div></form></x-ui.card>
        <x-ui.card title="Questions"><x-ui.data-table caption="Questions"><thead><tr><th>Key</th><th>Bank</th><th>Type</th><th>Versions</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($questions as $question)<tr><td data-label="Key">{{ $question->stable_key }}</td><td data-label="Bank">{{ $question->bank?->name }}</td><td data-label="Type">{{ str_replace('_', ' ', ucfirst($question->type)) }}</td><td data-label="Versions">{{ $question->versions->count() }}</td><td data-label="Status"><x-ui.status-badge :status="$question->status" /></td><td data-label="Action"><x-ui.button variant="secondary" wire:click="toggleQuestion({{ $question->id }})" loading="toggleQuestion">{{ $question->status === 'active' ? 'Deactivate' : 'Activate' }}</x-ui.button></td></tr>@empty<tr><td colspan="6"><x-ui.empty-state title="No questions" message="Create a question in the selected bank." /></td></tr>@endforelse</tbody></x-ui.data-table></x-ui.card>
    @endif
</div>
