@props(['report' => 'class'])
<x-ui.card title="Report filters" class="mb-6" x-data="{ year: '{{ request('academic_year_id') }}', classId: '{{ request('class_id') }}' }">
    <form method="GET" action="{{ route('admin.attendance.reports.'.($report === 'monthly' ? 'monthly' : $report), ['school' => $school]) }}" class="grid gap-4 sm:grid-cols-2 lg:grid-cols-5" @submit="loading = true" x-data="{ loading: false }">
        @if($report === 'monthly')<x-ui.input type="month" name="month" label="Month" value="{{ request('month', $month ?? now()->format('Y-m')) }}" :error="$errors->first('month')" required />@else<x-ui.select name="academic_year_id" label="Academic year" x-model="year" @change="classId = ''; $refs.section.value = ''"><option value="">All academic years</option>@foreach($years as $yearOption)<option value="{{ $yearOption->id }}" @selected((string) request('academic_year_id') === (string) $yearOption->id)>{{ $yearOption->name }}</option>@endforeach</x-ui.select><x-ui.select name="class_id" label="Class" x-model="classId" @change="$refs.section.value = ''"><option value="">All classes</option>@foreach($classes as $classOption)<option value="{{ $classOption->id }}" @selected((string) request('class_id') === (string) $classOption->id)>{{ $classOption->name }}</option>@endforeach</x-ui.select><x-ui.select name="section_id" label="Section" x-ref="section" :disabled="!request('class_id')"><option value="">All sections</option>@foreach($sections as $sectionOption)<option value="{{ $sectionOption->id }}" data-class="{{ $sectionOption->class_id }}" @selected((string) request('section_id') === (string) $sectionOption->id)>{{ $sectionOption->name }} · {{ $sectionOption->academicClass?->name }}</option>@endforeach</x-ui.select>@if($report === 'daily')<x-ui.date-input name="date" label="Date" value="{{ request('date') }}" />@endif@endif
        <div class="flex items-end gap-2"><x-ui.button type="submit">Apply filters</x-ui.button><a href="{{ route('admin.attendance.reports.'.($report === 'monthly' ? 'monthly' : $report), ['school' => $school]) }}" class="ui-button ui-button-secondary">Clear</a></div>
        <div x-show="loading" x-cloak class="flex items-center gap-2 text-sm text-slate-600" role="status" aria-live="polite"><x-ui.loading-state label="Loading report…" /></div>
    </form>
    @if(request()->query())<p class="mt-4 text-sm text-slate-600" role="status">Active filters: @foreach(request()->only(['academic_year_id','class_id','section_id','date','month']) as $key => $value){{ str_replace('_', ' ', ucfirst($key)) }}={{ $value }}@if(!$loop->last), @endif @endforeach</p>@endif
</x-ui.card>
